### ISSUE TITLE
Deebot N8 not showing up in Home

### ISSUE THREAD

**Issue by Cardo1** [bwp91/homebridge-deebot#103]
### What issue do you have? Please be as thorough and explicit as possible.
I have just installed the plugin to use alongside a Deebot N8.  The plugin fires up and detects the vacuum cleaner, however this does not appear in Home.  Under Accessories in the HB GUI it shows the vacuum battery state, however no switch.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge with config-ui

* Which version of Homebridge/HOOBS do you have?
1.6.0

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
5.3.0

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
Deebot N8

Shows as Class (Resource) - ty84oi (1sn1)

### Please paste any relevant logs below.
The logs show the accessory being recognised.  I can paste the logs, if necessary.

**Comment by bwp91** [comment]
Hi @Cardo1 

In the Home app do you see any reference to the accessory? Like the battery state?

Just to rule this out - if you have set the plugin up as a child bridge, have you added the separate QR code to the home app?

**Comment by Cardo1** [comment]
> Hi @Cardo1
> 
> In the Home app do you see any reference to the accessory? Like the battery state?
> 
> Just to rule this out - if you have set the plugin up as a child bridge, have you added the separate QR code to the home app?

Hi, thanks for the quick reply.  There was no reference to the accessory whatsoever in Home or any other HK apps I use.  I set the plugin to run as a child bridge and now the vacuum is showing up in Home and is all working correctly.

**Comment by bwp91** [comment]
Ah excellent. In fact earlier today I bought myself an N8 so I am looking forward to getting this!

**Comment by bwp91** [comment]
Closing as i believe issue is fixed
