### ISSUE TITLE
Option to hide motion sensor

### ISSUE THREAD

**Issue by DaveM8686** [bwp91/homebridge-deebot#11]
I absolutely love this plugin, thanks so much for it, but is it possible to have the option to hide the motion sensor, the same way you can hide the battery humidity sensor?  I basically only want the two switches for start cleaning and send to base.

**Comment by bwp91** [comment]
Hi @DaveM8686 

Thanks for this suggestion. Please update to the newest beta of the plugin v2.8.0-5 ([instructions](https://github.com/bwp91/homebridge-deebot/wiki/Beta-Version)) and through the Homebridge/HOOBS UI you should see a new configuration option 'Hide Motion Sensor'. Setting this to true/yes should hide the motion sensor after a restart.

Let me know how it goes!

**Comment by DaveM8686** [comment]
Thanks so much for your quick response! That worked great!
