### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by suivezlemir** [bwp91/homebridge-deebot#112]
Hello !

Do you know if your home bridge plugin would work with a Yeedi Vac 2 pro ? It seems EcoVacs Deebot / Yeedi are from the same company.

Thanks !

Antoine

**Comment by mrbungle64** [comment]
@suivezlemir 

I'm not sure if anyone has already confirmed it, but the yeedi Vac 2 pro should work.
Please give us feedback when you have it in use.

**Comment by suivezlemir** [comment]
Great ! Thank you for the quick answer, I'll confirm as soon as I can.

**Comment by mrbungle64** [comment]
@suivezlemir 

You have to enable "Use Yeedi Login" in the settings.

**Comment by suivezlemir** [comment]
Yep just done it now while setting the plugin up :) Thanks for the follow up !

**Comment by bwp91** [comment]
@mrbungle64 thanks for helping here (as always!)

yes please let us know if the device works correctly!

**Comment by suivezlemir** [comment]
Hello !

I'm getting this error when I try to activate the robot through HomeKit 

[Yeedi] sent error [DNS lookup failed: getaddrinfo ENOTFOUND portal-eu.ecouser.net].

All the setup when swimmingly though, robot is recognised, homebridge gets the battery % accurately etc.

I set up predefined areas also, following the instructions. If that changes anything.

**Comment by mrbungle64** [comment]
@suivezlemir 

> I'm getting this error when I try to activate the robot through HomeKit
> [Yeedi] sent error [DNS lookup failed: getaddrinfo ENOTFOUND portal-eu.ecouser.net].

Does the error still persist?
Is your network and internet connection working properly?

**Comment by suivezlemir** [comment]
It does persist, but come up only once per homebridge restart (on Raspberry Pi). E.g. homebridge restarts, I switch "clean" in homekit, I get the error again.

And yes my internet connection is 100% stable.

Weird thing is:
1) When I use the yeedi app (launch robot, change settings) I can see the info is received by homebridge / the plugin, and updates homekit in real time (both the clean / go charge switches).
2) When I use homekit (or eve) I can see commands in the homebridge log but nothing happens.

Thanks for the support btw, but if its too much of a pain, no worries I'll use the app instead.

**Comment by mrbungle64** [comment]
@suivezlemir 

What do you mean with "too much of a pain"?

> When I use homekit (or eve) I can see commands in the homebridge log but nothing happens.

I think I know what maybe cause this problem, but I'm not sure if you still want to continue ...

**Comment by suivezlemir** [comment]
oh I'm all in to continue haha, I was just saying if it is too time consuming to help me I'd understand if you want to stop (I don't want to waste your free time !)

**Comment by mrbungle64** [comment]
> oh I'm all in to continue haha, I was just saying if it is too time consuming to help me I'd understand if you want to stop (I don't want to waste your free time !)

ok, do you know where the homebridge directory is located?
You can open the file `models.js` in the directory `[homebridge directory]/node-modules/ecovacs-deebot.js/library` and change the value `950type_V2` for "yeedi vac 2 pro" from `false` to `true` (should be currently line 573).

After that it should work (maybe a restart of homebridge is needed).

**Comment by suivezlemir** [comment]
thanks for that, I did change the value but I didn't work unfortunately

**Comment by mrbungle64** [comment]
> thanks for that, I did change the value but I didn't work unfortunately

You can also try if it's working if you change `950type` and `950type_V2` to `false`.
But I'm pretty sure that both values have to be `true` ...

Btw.: `950type` = `false` and `950type_V2` = `true` is not a valid combination.

**Comment by suivezlemir** [comment]
I tried both values at false, and again both at true but unfortunately it didn't work either.

**Comment by mrbungle64** [comment]
> I tried both values at false, and again both at true but unfortunately it didn't work either.

Have you restarted Homebridge after making the changes?

I'm not sure how Homebridge handles this ... 
@bwp91, maybe there's more needed than restarting?

**Comment by suivezlemir** [comment]
yes each time to be sure

**Comment by mrbungle64** [comment]
@suivezlemir 

Does sending the device back to the charging station work via HomeKit?

**Comment by suivezlemir** [comment]
@mrbungle64 

Unfortunately not, nor switching the "clean" mode on. Nor the homekit / eve scenes to clean predefined areas.

**Comment by mrbungle64** [comment]
@suivezlemir 

Can you please post the log output?

**Comment by mrbungle64** [comment]
@suivezlemir 

I just found out that the Yeedi Vac 2 pro is already confirmed to work with my library.
Can you please reinstall the plugin and try again?

**Comment by mrbungle64** [comment]
@suivezlemir 

Which version of the plugin do you have installed?
Maybe you have to use the beta version:
https://github.com/bwp91/homebridge-deebot/wiki/Beta-Version

**Comment by mrbungle64** [comment]
@suivezlemir 

Is it working now or did you lose interest?

**Comment by suivezlemir** [comment]
@mrbungle64 

Apologies I missed your previous message. No still not working. I install the plugin directly from Homebridge, so unlikely it's the beta version. I uninstalled / reinstalled (using the instructions and the "disable plugin" option), and still nothing. I might need to do a full homebridge reinstall.

**Comment by mrbungle64** [comment]
> I uninstalled / reinstalled (using the instructions and the "disable plugin" option), and still nothing. I might need to do a full homebridge reinstall.

@bwp91, any suggestions that might help?

**Comment by mrbungle64** [comment]
@suivezlemir 

Any news on this?
