### ISSUE TITLE
"sending update [GetNetInfo]." log spam

### ISSUE THREAD

**Issue by bondskin** [bwp91/homebridge-deebot#114]
Hi,

Thank you for this plugin, it works very well.
Would it be possible to add an option to suppress the repeating (every 2min) log entry saying "sending update [GetNetInfo]."?

cheers
Mike

**Comment by bwp91** [comment]
Hey @bondskin sorry for delay in reply to this.

this message _should_ only appear when the plugin debug option is enabled.

Since (my fault!) it's been a long time since you opened this issue, I am gonna close it now.
Please do re-open if you are still seeing this entry appear in the log unnecessarily!

Thanks
Ben

**Comment by bondskin** [comment]
Hi @bwp91 ,

Many thanks for coming back on this topic.
Just to be clear, you are referring to this option, right?
<img width="671" alt="SCR-20230312-iftf" src="https://user-images.githubusercontent.com/55050117/224531516-eeb3e25a-2eeb-45d5-97a8-8c27a4bb1b1d.png">
Because it does not say "debug".

With this option currently being disabled (as shown), I still see the log events

> [12/03/2023, 08:33:21] [Deebot] [Frau Kleinert] sending update [GetNetInfo].
> [12/03/2023, 08:38:21] [Deebot] [Frau Kleinert] sending update [GetNetInfo].

**Comment by bwp91** [comment]
Hi @bondskin 

please try v6.0.1, i should have had a proper check of the code - this message was (as you said) appearing even without debugging option enabled!

**Comment by bondskin** [comment]
Hi @bwp91 ,

after updating and restarting HB, I see the following

> [16/03/2023, 08:57:23] [Deebot] ***** Disabling plugin. *****
> [16/03/2023, 08:57:23] [Deebot] ***** connect ETIMEDOUT 3.64.122.218:443 at Function.AxiosError.from (/usr/lib/node_modules/homebridge-deebot/node_modules/axios/lib/core/AxiosError.js:89:14). *****

**Comment by bondskin** [comment]
Update, I have updated my python3 to latest release (from 3.7 to 3.10.10) - unrelated to this topic; and re-installed the latest update of this plugin to 6.0.1 
Now all looks good
