### ISSUE TITLE
China Server Support

### ISSUE THREAD

**Issue by andrewsfchoi** [bwp91/homebridge-deebot#12]
### What issue do you have? Please be as thorough and explicit as possible.
Installed plugin, was confused with the required fields as my Deebot is on China Mainland server. The China Mainland server uses mobile number to login, so I tried to use that as login credentials (username field) which didn't work. In the Ecovacs App, after logging in with mobile number, I can see my account was given an "Ecovacs ID". I tried using that ID in the Hoobs config in lieu of mobile number, and still wouldn't work.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
3.3.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Rasp Pi 4

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
2.8.3

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
Deebot T8 Aivi +

### Please paste any relevant logs below.

2021-02-10, 3:04:11 AM [Deebot] [v2.8.3] initialised. Syncing with ECOVACS.
2021-02-10, 3:04:11 AM Bridge is running on port 51826.
2021-02-10, 3:04:11 AM [Deebot] ***** Disabling plugin [v2.8.3]. *****
2021-02-10, 3:04:11 AM [Deebot] ***** getaddrinfo EAI_AGAIN eco-cn-api.ecovacs.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26). *****
```

```

**Comment by bwp91** [comment]
Hi @andrewsfchoi 

In the present state the plugin doesn't support login for users from China.

After speaking with the developer of `ecovacs-deebot` (the library that this plugin uses to communicate with deebot devices), it seems that some updates to the code would be needed to support user accounts from China.

We would need a user from China to help us test these changes... would you be willing to help us out so we can support this?

It would involve installing beta versions of this plugin.

Thanks

**Comment by andrewsfchoi** [comment]
I'm using a China bought Deebot, on Mainland server. I'm based in Hong Kong. I can't say I have the technical skills, but I'm willing to donate my time and effort to pursue this. As long as there are clear instructions, would be a good pandemic project :)

**Comment by bwp91** [comment]
Hey @andrewsfchoi 

A test version of the plugin is now available for trying. You can update to this test version in HOOBS by doing the following:

1. Stop the HOOBS service via the Main Menu -> Stop Service
2. Then go to the terminal which is also in Main Menu -> Terminal and run the following commands one at a time:
    ```
    cd ~/.hoobs/
    ```
    ```
    npm install homebridge-deebot@beta
    ```
3. Once this has finished, start the HOOBS service again
4. Go to the homebridge-deebot configuration and enter your `Ecovacs ID` as your username
5. Once you've saved the config, HOOBS should automatically restart

It would be worth watching the logs at this point to see if it has been successful. If you get any network error messages then you may need to change your deebot country code from `CN` to `WW` and restart HOOBS again.

Please let us know how you get on!

**Comment by andrewsfchoi** [comment]
this is what showed up:

hoobs@hoobs:/home/hoobs/.hoobs/etc $ cd ~/.hoobs/
hoobs@hoobs:/home/hoobs/.hoobs $ npm install homebridge-deebot@beta
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN checkPermissions Missing write access to /home/hoobs/.hoobs/node_modules/hap-nodejs
npm WARN notsup Unsupported engine for homebridge-deebot@2.9.0-0: wanted: {"homebridge":"^1.1.7","node":"^14.15.5"} (current: {"node":"14.15.1","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-deebot@2.9.0-0

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/hoobs/.hoobs/node_modules/hap-nodejs
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR!  [Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/hap-nodejs'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-02-13T15_40_11_028Z-debug.log
hoobs@hoobs:/home/hoobs/.hoobs $

**Comment by bwp91** [comment]
Did you stop HOOBS first?

**Comment by andrewsfchoi** [comment]
You're right, this is what shows up with the service stopped

hoobs@hoobs:/home/hoobs/.hoobs/etc $ cd ~/.hoobs/
hoobs@hoobs:/home/hoobs/.hoobs $ npm install homebridge-deebot@beta
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js

> canvas@2.6.1 install /home/hoobs/.hoobs/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@14.15.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.83-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/hoobs/.hoobs/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/hoobs/.hoobs/node_modules/canvas/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/hoobs/.hoobs/node_modules/canvas
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/hoobs/.hoobs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/hoobs/.hoobs/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/hoobs/.hoobs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.83-v7l+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/hoobs/.hoobs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/hoobs/.hoobs/node_modules/canvas
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/hoobs/.hoobs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/hoobs/.hoobs/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN notsup Unsupported engine for homebridge-deebot@2.9.0-0: wanted: {"homebridge":"^1.1.7","node":"^14.15.5"} (current: {"node":"14.15.1","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-deebot@2.9.0-0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.6.1 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ homebridge-deebot@2.9.0-0
updated 1 package and audited 461 packages in 16.183s

31 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (4 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
hoobs@hoobs:/home/hoobs/.hoobs $

**Comment by bwp91** [comment]
This is okay, despite all the waffle there it has installed correctly. Next onto the trying the credentials with your ecovacs id!

**Comment by andrewsfchoi** [comment]
nice, worked with WW, device created and add on home app, 2 switch and one motion sensor advertised

however, nothing happens when I flip the "clean" or "go charge" switches

**Comment by mrbungle64** [comment]
@andrewsfchoi 

Is the battery level displayed?

**Comment by andrewsfchoi** [comment]
Nope, shows 0% and not charging

**Comment by mrbungle64** [comment]
@andrewsfchoi

> Nope, shows 0% and not charging

Please start the cleaning with the mobile app and check again if the battery value displayed.

**Comment by mrbungle64** [comment]
@bwp91 

Can you please output the `deviceClass` in debug mode?

**Comment by andrewsfchoi** [comment]
> @andrewsfchoi
> 
> > Nope, shows 0% and not charging
> 
> Please start the cleaning with the mobile app and check again if the battery value displayed.

0%

**Comment by mrbungle64** [comment]
@andrewsfchoi 

Can you please post the log output? If possible in debug mode

cc: @bwp91

**Comment by bwp91** [comment]
Hi @andrewsfchoi 

I have just released another test version of the plugin. In a few minutes (it might take a few mins for the update to become available), could you use the same method I provided earlier to update to the new version.

Once installed you should these lines at the end

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

homebridge-deebot@2.9.0-1
updated 1 package and audited 461 packages in 16.183s
31 packages are looking for funding
run npm fund for details

found 5 vulnerabilities (4 low, 1 high)
run npm audit fix to fix them, or npm audit for details
hoobs@hoobs:/home/hoobs/.hoobs $
```

The important part being the `homebridge-deebot@2.9.0-1` line where the version should show as 2.9.0-1.

Then restart HOOBS and in the logs you should see an extra line, something like:

```
[13/02/2021, 16:29:05] [Deebot] [Device] isDeviceClass950type:...
```

Could you provide this line from your log?

**Comment by andrewsfchoi** [comment]
I only see this

2021-02-14, 12:42:41 AM [Deebot] [v2.9.0-1] initialised. Syncing with ECOVACS.
2021-02-14, 12:42:41 AM Bridge is running on port 51826.
2021-02-14, 12:42:42 AM Miio Device (ip: 192.168.1.25) is now connected
2021-02-14, 12:42:42 AM [Deebot] ***** Disabling plugin [v2.9.0-1]. *****
2021-02-14, 12:42:42 AM [Deebot] ***** getaddrinfo EAI_AGAIN gl-ww-api.ecovacs.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26). *****

**Comment by bwp91** [comment]
Please wait a couple of minutes and then do the same process to update to a newer version 2.9.0-2.

The error you received above is most probably a temporary network error which could resolve once you have restarted HOOBS.

Once this new version is installed you won't see the `isDeviceClass950type` log line, but you should see a few lines with info about your device, something like:

```
[13/02/2021, 16:43:57] [Deebot] [Hoover] initialised with id E200##############.
[13/02/2021, 16:43:57] [Deebot] {
  did: 'E##########',
  name: 'E############',
  class: '#####',
  resource: '#####',
  nick: '####',
  company: 'ec#####'
}
```

**Comment by andrewsfchoi** [comment]
2021-02-14, 12:53:56 AM [Deebot] [v2.9.0-2] initialised. Syncing with ECOVACS.
2021-02-14, 12:53:56 AM Bridge is running on port 51826.
2021-02-14, 12:53:56 AM [Deebot] ***** Disabling plugin [v2.9.0-2]. *****
2021-02-14, 12:53:56 AM [Deebot] ***** getaddrinfo EAI_AGAIN gl-ww-api.ecovacs.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26). *****

**Comment by mrbungle64** [comment]
@andrewsfchoi

> 2021-02-14, 12:53:56 AM [Deebot] [v2.9.0-2] initialised. Syncing with ECOVACS.
> 2021-02-14, 12:53:56 AM Bridge is running on port 51826.
> 2021-02-14, 12:53:56 AM [Deebot] ***** Disabling plugin [v2.9.0-2]. *****
> 2021-02-14, 12:53:56 AM [Deebot] ***** getaddrinfo EAI_AGAIN gl-ww-api.ecovacs.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26). *****

I guess that you're using `WW` as value for country in your config ...

**Comment by bwp91** [comment]
Do you have internet connectivity issues at all? There seems to be an issue with your HOOBS box accessing the ecovacs server, but since you have the accessory switches and motion sensor in HOOBS it must have worked at some point.

It'll be a case of restarting HOOBS every now and again until it works

**Comment by mrbungle64** [comment]
> @andrewsfchoi
> 
> > 2021-02-14, 12:53:56 AM [Deebot] [v2.9.0-2] initialised. Syncing with ECOVACS.
> > 2021-02-14, 12:53:56 AM Bridge is running on port 51826.
> > 2021-02-14, 12:53:56 AM [Deebot] ***** Disabling plugin [v2.9.0-2]. *****
> > 2021-02-14, 12:53:56 AM [Deebot] ***** getaddrinfo EAI_AGAIN gl-ww-api.ecovacs.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26). *****
> 
> I guess that you're using `WW` as value for country in your config ...

should be `gl-cn-api.ecovacs.com` not `gl-ww-api.ecovacs.com`

Please check the value of country in your config

**Comment by andrewsfchoi** [comment]
I changed to CN for country code

2021-02-14, 1:03:36 AM [Deebot] [b3850773-f76c-43e0-bb2e-9ac524e60f1e] initialised with id b3850773-f76c-43e0-bb2e-9ac524e60f1e.
2021-02-14, 1:03:36 AM [Deebot] {
  did: 'b3850773-f76c-43e0-bb2e-9ac524e60f1e',
  name: 'E0BG14202B09HFQ70190',
  class: 'vdehg6',
  resource: 'm8rr',
  nick: null,
  company: 'eco-ng',
  bindTs: 1611822528574,
  service: {
    jmq: 'jmq-ngiot-cn.dc.cn.ecouser.net',
    mqs: 'api-ngiot.dc-cn.cn.ecouser.net'
  }
}
2021-02-14, 1:03:36 AM [Deebot] ✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
2021-02-14, 1:03:36 AM Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/home/hoobs/.hoobs/node_modules/ecovacs-deebot/node_modules/mqtt/lib/client.js:1190:15)
    at MqttClient._handlePacket (/home/hoobs/.hoobs/node_modules/ecovacs-deebot/node_modules/mqtt/lib/client.js:424:12)
    at work (/home/hoobs/.hoobs/node_modules/ecovacs-deebot/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/home/hoobs/.hoobs/node_modules/ecovacs-deebot/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/home/hoobs/.hoobs/node_modules/ecovacs-deebot/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/hoobs/.hoobs/node_modules/ecovacs-deebot/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/home/hoobs/.hoobs/node_modules/ecovacs-deebot/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at TLSSocket.ondata (_stream_readable.js:719:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
2021-02-14, 1:03:36 AM Got SIGTERM, shutting down Bridge...

**Comment by andrewsfchoi** [comment]
crashes my service, but I see those additional log lines

**Comment by bwp91** [comment]
@andrewsfchoi me and you can have a little tea break while @mrbungle64 tries to find out what is causing the `Connection refused: Not authorized` problem 😛

**Comment by bwp91** [comment]
Hi @andrewsfchoi 

In a couple of minutes please update the plugin again to v2.9.0-3 to see if this resolves the `Connection refused: Not authorized` issue.

Thanks

**Comment by andrewsfchoi** [comment]
Its working now!
Thanks this is awesome

2021-02-14, 1:44:31 AM - [Deebot] [b3850773-f76c-43e0-bb2e-9ac524e60f1e] initialised with id b3850773-f76c-43e0-bb2e-9ac524e60f1e.
2021-02-14, 1:44:31 AM - [Deebot] {
  did: 'b3850773-f76c-43e0-bb2e-9ac524e60f1e',
  name: 'E0BG14202B09HFQ70190',
  class: 'vdehg6',
  resource: 'm8rr',
  nick: null,
  company: 'eco-ng',
  bindTs: 1611822528574,
  service: {
    jmq: 'jmq-ngiot-cn.dc.cn.ecouser.net',
    mqs: 'api-ngiot.dc-cn.cn.ecouser.net'
  }
}
2021-02-14, 1:44:31 AM - [Deebot] ✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
2021-02-14, 1:44:32 AM - [Deebot] [b3850773-f76c-43e0-bb2e-9ac524e60f1e] current battery [100%].
2021-02-14, 1:44:33 AM - [Deebot] [b3850773-f76c-43e0-bb2e-9ac524e60f1e] current cleaning state [idle].
2021-02-14, 1:44:33 AM - [Deebot] [b3850773-f76c-43e0-bb2e-9ac524e60f1e] current charging state [charging].

**Comment by mrbungle64** [comment]
> Its working now!
> Thanks this is awesome
> 

Yesss! 😄

**Comment by bwp91** [comment]
I'll mark this as complete now. This functionality is currently available in the beta version and will be available in the next version of the plugin!

Thanks @andrewsfchoi for your patience testing this and thanks to @mrbungle64 too for actually implementing it :)

**Comment by gallevy2003** [comment]
Hi
I bought x1 omni from aliexpress, can I change the region to israel?
Thanks
