### ISSUE TITLE
General question 

### ISSUE THREAD

**Issue by k6iso** [bwp91/homebridge-deebot#133]
Hey there!
Great job on the Deebot plugin. 
I’m super new to this so excuse me if I have dumb questions… lol

Is there a way to rename the action e.g. 
go charge -> return to base 

Also is there more optional configs not listed? Wondering if I can pause Deebot and then then have it continue.  

Thanks !

**Comment by bwp91** [comment]
> I’m super new to this so excuse me if I have dumb questions… lol

No dumb questions!

> Is there a way to rename the action e.g. go charge -> return to base

Not in the home app - tho you could probably create a homekit scene do perform the same action with a name of your choice?

> Also is there more optional configs not listed? Wondering if I can pause Deebot and then then have it continue.

There aren't any extra config options right now, to "pause" this might work the same as just turning the *Clean* button off and on again? I realise this may not be exactly what you are looking for as this potentially stops the current clean program and then starts again.

Feel free to ask away

**Comment by k6iso** [comment]
Haha. All good.
Thanks Ben!

On Apr 26, 2023, at 6:49 PM, Ben ***@***.***> wrote:

﻿

I’m super new to this so excuse me if I have dumb questions… lol

No dumb questions!

Is there a way to rename the action e.g. go charge -> return to base

Not in the home app - tho you could probably create a homekit scene do perform the same action with a name of your choice?

Also is there more optional configs not listed? Wondering if I can pause Deebot and then then have it continue.

There aren't any extra config options right now, to "pause" this might work the same as just turning the Clean button off and on again? I realise this may not be exactly what you are looking for as this potentially stops the current clean program and then starts again.

Feel free to ask away

**Comment by bwp91** [comment]
Nice 😁
Any future issues or requests please do get in touch!
