### ISSUE TITLE
Setup spot area not working as expected

### ISSUE THREAD

**Issue by datarepos76** [bwp91/homebridge-deebot#149]
Hi,

I am currently trying to setup my new Deebot Ozmo 950. The map setup is finished and the renaming of the areas is completed. Installation is as follows:

Homebridge Deebot 6.1.1
Homebridge 3.0.17
Synology ﻿DSM 7.2-64570 Update 3
Node.js 18.15.0-1008

I am trying to find the spot areas in Homebridge log as described, but cannot find them. The log is attached. I have tryed to but the pugin to debug mode with configuration entry "debug": "true" but no success.

Could you help me out? Many thanks in advance.

Mathias

**Comment by datarepos76** [comment]
[hblog.txt](https://github.com/bwp91/homebridge-deebot/files/12699026/hblog.txt)

**Comment by silenceJT** [comment]
I got exactly the same problem

**Comment by silenceJT** [comment]
@datarepos76 Hi mate, I installed beta version and it did show all the map area info

<img width="536" alt="image" src="https://github.com/bwp91/homebridge-deebot/assets/28582784/42a3c3f1-7080-4134-ad2b-d572a77d4187">

**Comment by datarepos76** [comment]
This worked for me 👍 Thank you 😊
