### ISSUE TITLE
Motion Sensor permanent

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-deebot#24]
Hi Ben,
Reporting the motion detection "false" in the config not work in HomeKit when the sensor still be part of the sensor list 
How can I definitely remove it from HK?![image](https://user-images.githubusercontent.com/70729310/116320004-bad05000-a7b7-11eb-9c7c-6ffe0de46c72.jpeg)

![image](https://user-images.githubusercontent.com/70729310/116320018-c0c63100-a7b7-11eb-9c1e-20b0044da8fc.png)

**Comment by bwp91** [comment]
Hi @Stetocasa 

The configuration changed in version 3 for a 'per device' configuration (a bit like ewelink and govee plugins).

You will need to update your config to something like:

```json
"countryCode": "IT",
"devices": [
   {
      "deviceId": "############",
      "hideMotionSensor": true,
      "lowBattThreshold": 20
   }
],
"name": "Zina",
...
```

where `deviceId` is the id of your Deebot which is shown in the logs when the plugin initialises:

```
[Zina] [Device] initialised with id ############.
```

All of the available options can be seen at:
https://github.com/bwp91/homebridge-deebot/wiki/Configuration#optional-settings

**Comment by Stetocasa** [comment]
In the wiki you mentioned that the device ID is for China country.
The plug-in works well, the only thing that I can remove is the motion sensor

**Comment by bwp91** [comment]
The wiki mentions the ECOVACS ID for users in China.

The device id is different and relates to the id of the deebot device.

If using the config that I posted above, the motion sensor should be removed from HomeKit

**Comment by Stetocasa** [comment]
Done but still in the sensor list 
![image](https://user-images.githubusercontent.com/70729310/116371577-de24ea80-a80b-11eb-9e4d-c27ba5ada4a0.jpeg)

**Comment by bwp91** [comment]
try changing `deviceID` to `deviceId`

**Comment by Stetocasa** [comment]
Great! Now work🥳
