### ISSUE TITLE
Device ID?

### ISSUE THREAD

**Issue by mmorper** [bwp91/homebridge-deebot#25]
For the life of me, I cannot find this string in the Ecovacs app… can you please point me in the right direction? Thanks in advance.

**Comment by bwp91** [comment]
Hi @mmorper 

I’m pretty sure the device id can’t be seen in the ecovacs app.

however it can be seen in the plugin-ui settings screen if you are running the homebridge-ui, it can also be seen in the logs when the plugin is initialising, you should see a log entry like

```
[Device] initialised with id %%%
```
