### ISSUE TITLE
Better handling of device online/offline log entries

### ISSUE THREAD

**Issue by itsthenewdc** [bwp91/homebridge-deebot#35]
### What issue do you have? Please be as thorough and explicit as possible.
When looking at the Logs in HOOBS, I see "[Deebot] [E0000671617600700096] sent error [Recipient unavailable]." spammed every 30 seconds, which is the refresh time set.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
3.3.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
HOOBS Box. Node 14.17.0.

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
3.0.3. Only version ever used.

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
Ozmo T8 AIVI

### Please paste any relevant logs below.

```
7/5/2021, 7:34:19 PM [Deebot] [E0000671617600700096] sent error [Recipient unavailable].
7/5/2021, 7:34:19 PM [Deebot] [E0000671617600700096] sent error [Recipient unavailable].
7/5/2021, 7:34:19 PM [Deebot] [E0000671617600700096] sent error [Recipient unavailable].
7/5/2021, 7:34:19 PM [Deebot] [E0000671617600700096] sent error [Recipient unavailable].
7/5/2021, 7:34:49 PM [Deebot] [E0000671617600700096] sent error [Recipient unavailable].
7/5/2021, 7:34:49 PM [Deebot] [E0000671617600700096] sent error [Recipient unavailable].
7/5/2021, 7:34:49 PM [Deebot] [E0000671617600700096] sent error [Recipient unavailable].
7/5/2021, 7:34:49 PM [Deebot] [E0000671617600700096] sent error [Recipient unavailable].
```

**Comment by bwp91** [comment]
Hi @itsthenewdc 

This error normally appears when the device is powered off or not connected to wifi. I will make a change to the plugin so the entry only appears **once** every X seconds.

Was this the idea for the issue?

Thanks

**Comment by itsthenewdc** [comment]
Something to severely limit the amount or disable completely would be great. The deebot is simply in its dock and the logs being spammed with that message that often seems excessive.

**Comment by bwp91** [comment]
For an immediate solution, you could update to the beta version ([instructions](https://github.com/bwp91/homebridge-deebot/wiki/Beta-Version#hoobs-ui)) of the plugin, and use the configuration to disable all logging for the accessory.

Since you're on HOOBS 3, the configuration is a little more complicated, but in the devices box (on the plugin configuration page) you could put this:

```json
[
   {
      "deviceId": "E2001229192000070375",
      "label": "My Device",
      "overrideLogging": "disable"
   }
]
```

**Comment by bwp91** [comment]
I have made some changes to the next version of the plugin, device online/offline notifications will appear just **once** each time a device goes offline, thus avoiding repeated `sent error [Recipient unavailable]` log entries.

Will hopefully release this update hopefully within the next few days.

**Comment by bwp91** [comment]
Plugin version 3.2.1 should make the logs look tidier :)

**Comment by itsthenewdc** [comment]
Works perfectly! Thank you!
