### ISSUE TITLE
Deebot Duplicates

### ISSUE THREAD

**Issue by itsthenewdc** [bwp91/homebridge-deebot#37]
### What issue do you have? Please be as thorough and explicit as possible.
After adding my credentials and getting everything setup, Homekit displays 2 versions of my Deebot (Ozmo T8 AIVI). One version shows the Model - DEEBOT OZMO T8 AIVI - and the controls appear to function correctly.. and the 2nd version shows what looks like to be the serial number as its name and the controls, although identical, don't display the correct states of the device and just always show as off. There's no way to remove the duplicated Deebot and its accessories, and I'd really prefer to not make a "junk" room to store these accessories.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
HOOBS 4.0.87, Homebridge 1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
HOOBS Box, Node 14.17.2

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
3.2.2

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
Ozmo T8 AIVI

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @itsthenewdc 

HOOBS 4 provides the option of removing a single accessory from the cache.

You can do this from Bridges -> (plugin bridge) -> "Cache"

You will be able to remove the 'stale' accessory.

Is it an accessory that keeps reappearing?

**Comment by itsthenewdc** [comment]
It was basically an exact duplicate of the Deebot that was the right/working one - showing clean/motion/etc. But that Cache solution did work - awesome! Thank you.

**Comment by bwp91** [comment]
The Homebridge accessory is linked to the physical device by the device ID. It's strange about the duplication since normally this could only happen if the device id changed, which I really doubt happened! So this is strange.

Perhaps _something_ went wrong with the Homebridge cache when you updated to HOOBS 4?

**Comment by itsthenewdc** [comment]
I'd have no way of confirming, but I'm pretty sure this duplication issue existed when I was on HOOBS 3, and I just now got around to trying to cleanup a bunch of my Homekit stuff.

**Comment by bwp91** [comment]
Ya, the removing a single accessory from the cache is a great feature of hoobs 4 👍

**Comment by itsthenewdc** [comment]
It seems that the duplicated device keeps coming back, despite being deleted from cache :( Any other way to keep this removed?

**Comment by bwp91** [comment]
Can you grab a screenshot of the HOOBS page showing your bridge cache page for this plugin?

**Comment by itsthenewdc** [comment]
<img width="731" alt="Screen Shot 2021-07-18 at 9 10 52 AM" src="https://user-images.githubusercontent.com/51030387/126068263-ccb0d250-559c-40bf-9805-5e9b24ad27f1.png">

**Comment by bwp91** [comment]
When you cleared the cache before, did you remove both accessories or just one of them?
The one you need to keep is with the UUID `cae487d8-3e7d-4d98-ad05-f103ec93b425`

**Comment by itsthenewdc** [comment]
I kept the other one, because that's the one in Homekit that was actually working (shows on when on, etc.) It's also the one that appears to be the most accurate in labeling. But I can try clearing "Downstairs" if you think that's the one to do.

<img width="540" alt="cae487d8-3e7d-4d98-ad05-f103ec93b425" src="https://user-images.githubusercontent.com/51030387/126068873-b3dbf3fb-1cda-40c8-a171-1da8365bf6a4.png">
<img width="541" alt="65bb8c57-aeb1-4359-8d86-dd135fd80478" src="https://user-images.githubusercontent.com/51030387/126068874-850ecda2-6cd3-4cdd-867f-aa2733b53d2e.png">

**Comment by bwp91** [comment]
the two pics you posted here are helpful. it looks like your device has two forms of serial number? i didn't realise this could be the case - i think the plugin is getting a bit mixed up.

From the two images, which serial number refers to the accessory you described: ??

> the one in Homekit that was actually working (shows on when on, etc.) It's also the one that appears to be the most accurate in labeling.

**Comment by itsthenewdc** [comment]
The one that works in Homekit is the one with the manufacturer of "eco-ng".
The one that does not work is "eco-legacy".
If it's helpful, I did delete the cache for eco-ng, but the remaining one (eco-legacy) still doesn't work.

**Comment by bwp91** [comment]
I have just released v3.3.0 of the plugin.

I'm not sure how long this will take to appear in HOOBS, you may need to clear the HOOBS cache (a different cache!) from Menu > Hub Settings > Clear Cache, so it pulls down the latest update info.

Once v3.3.0 appears, use the bridge settings to clear **both** accessories from the cache, restart the plugin and one new accessory should be created. I hope I have fixed this properly. Could you grab me a screenshot of the homekit data for this new accessory as you did for both devices before. and also just check that the controls work and the switches correctly update state even if the device is controlled physically. that would be great.

**Comment by bwp91** [comment]
If you’re still waiting for the update to appear, i’ve just realised, 

if you go to the plugins section, click on the deebot bridge then the deebot plugin, click on versions, and click on the icon next to 3.2.2 at the very top, in the window that appears click on the existing deebot bridge, this will actually install 3.3.0

**Comment by itsthenewdc** [comment]
Got it installed, cleared the cache of both, but upon restart it brought back both.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/51030387/126073603-34839a15-2d5a-4126-b0e1-12ee7b3ea5b4.png">
<img width="544" alt="image" src="https://user-images.githubusercontent.com/51030387/126073609-fa251b79-7a94-4f51-a045-2c1105b35e69.png">

**Comment by mrbungle64** [comment]
@itsthenewdc 

For me it looks like there's an older Deebot device still registered in your Ecovacs account:
* manufacturer `eco-legacy`
* model `113`

Have you used another Deebot device with this account before?

**Comment by itsthenewdc** [comment]
I'm not sure if I have. If I did, it would have been many years ago since it's definitely been awhile. I don't see a way in app or on the website to see older devices.

**Comment by mrbungle64** [comment]
@itsthenewdc 

If you swipe to the left in the device overview page of the mobile app is there another model listet?

**Comment by itsthenewdc** [comment]
Nope, just the one.

**Comment by mrbungle64** [comment]
@itsthenewdc 

I'm pretty sure model `113` (`eco-legacy`) is not related to your T8 AIVI because the T8 AIVI models have different class (e.g. `x5d34r`).
I assume that it's releated to an very old model (e.g. Deebot Slim). Maybe one of the first models with Wifi capabilities.

**Comment by bwp91** [comment]
@itsthenewdc 

You can use the plugin settings to remove and ignore this 'other' accessory from hoobs.

Create an entry for it in the devices section with the serial number `E0000671617600700096` and tick the 'Hide from HomeKit' option. 

When the bridge restarts it should remove this accessory just leaving the correct one for you to use

**Comment by itsthenewdc** [comment]
That seems to have done the trick. Hopefully stays that way ^_^
