### ISSUE TITLE
Ecovacs stop and start

### ISSUE THREAD

**Issue by marclombardi11** [bwp91/homebridge-deebot#44]
### Hoobs

* Which version of Homebridge/HOOBS do you have? V4

* Raspberry Pi 4

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version? Official Ecovacs Hoobs

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable. Deebot 500

### Please paste any relevant logs below.

```

```

**Comment by mrbungle64** [comment]
@marclombardi11 
Please try if it's working when you reinstall the plugin

@bwp91 
I just published version 0.6.8 of the library

**Comment by bwp91** [comment]
@marclombardi11 either reinstall as suggested above or update to the v4.2.5 i have just released.

has this fixed your issue?

@mrbungle64 thanks!

**Comment by marclombardi11** [comment]
That did thank you
