### ISSUE TITLE
Custom  areas 

### ISSUE THREAD

**Issue by Colequi1** [bwp91/homebridge-deebot#45]
Hi, I’m new into this, after I configured the plugin I was able to identify the custom spot areas in the debug log. But, inte settings, when I select the custom areas part, there is no option to add custom areas or the area’s numbers or combinations? 
thanks!!

**Comment by bwp91** [comment]
Hi @Colequi1 

The custom area fields will appear once you have entered a value for the "Label" and "Device ID" for your device:

<img width="352" alt="Screenshot 2021-11-02 at 07 26 11" src="https://user-images.githubusercontent.com/43026681/139803540-01db6b1c-cce9-4003-b92d-cfa6a2a76f9c.png">

**Comment by Colequi1** [comment]
Oh!! Didn’t even think to write something there.. thank you!!
