### ISSUE TITLE
Custom areas and max speed 

### ISSUE THREAD

**Issue by Colequi1** [bwp91/homebridge-deebot#46]
Hi again, so I was able to add the custom areas after adding the device ID 
But it doesn’t appear on the eve app
Also max speed doesn’t appear
Here is my current json config
![FD718E01-5039-43B6-A42F-7D048C3739BB](https://user-images.githubusercontent.com/93551654/140033654-edbf607a-6df9-4fbf-bd24-9439968e1a92.jpeg)

**Comment by bwp91** [comment]
From within the Eve app, you need to click on the "Clean" accessory, and the various buttons should appear in there...

They don't appear in the list like "Clean", "Go Charge", you actually need to go inside the Clean accessory... have you looked in there?

**Comment by Colequi1** [comment]
My ignorance never seizes to amaze me.
Just found everything there!
Thanks a lot!
