### ISSUE TITLE
Custom areas not showing up in Eve app

### ISSUE THREAD

**Issue by ymohiuddin** [bwp91/homebridge-deebot#47]
### What issue do you have? Please be as thorough and explicit as possible.
Hi I've installed the Ecovacs plugin and am trying to use the custom areas feature. Everything seems to be working and there are no errors on the log - but I'm not seeing the button for areas on the Eve app.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
4.1.11

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
4.2.7

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
Deebot T8+

### Please paste any relevant logs below.

![Screen Shot 2021-11-05 at 1 41 09 PM](https://user-images.githubusercontent.com/88597993/140555097-57c05a17-3dbf-4ad0-999e-21921125dfca.png)
![Screen Shot 2021-11-05 at 1 41 41 PM](https://user-images.githubusercontent.com/88597993/140555119-f79cac56-926a-44dd-85eb-ccae8f809acb.png)
![Screen Shot 2021-11-05 at 1 42 19 PM](https://user-images.githubusercontent.com/88597993/140555127-c67ae60d-0847-40e5-8948-0612f7d30644.png)

**Comment by bwp91** [comment]
Hi @ymohiuddin 

the buttons should appear inside the "Clean" accessory, not in the list of "Clean" and "Go Charge".

**Comment by ymohiuddin** [comment]
This is all I am seeing in the Deebot accessory
![IMG_0758](https://user-images.githubusercontent.com/88597993/140556379-052378ef-b955-444b-b2af-acb97ccfbd11.PNG)

**Comment by bwp91** [comment]
With plugin debug logging on (which I think you already do), can you restart the plugin/bridge and paste here all the logs that appear for the plugin initialising?

**Comment by ymohiuddin** [comment]
Here it is.
![Screen Shot 2021-11-05 at 2 53 53 PM](https://user-images.githubusercontent.com/88597993/140563892-9b1167d1-321a-4949-b14b-6cc14a30773e.png)

**Comment by bwp91** [comment]
What have you used as the device id in the configuration?

**Comment by bwp91** [comment]
I think you may need to use the device ID starting with `beb330c1-...` rather than the `E0640...` number

**Comment by ymohiuddin** [comment]
Where do I put in the device ID field? I didn’t put anything in there because I thought it was optional.

Yaseen Mohiuddin
***@***.***

**Comment by ymohiuddin** [comment]
I put the serial number in and it worked! Thank you.

Yaseen Mohiuddin
***@***.***

**Comment by bwp91** [comment]
Yes the device id is required so the plugin can link the spot areas to this specific device. 

This is in case you have multiple devices, the plugin can link specific config to a specific device
