### ISSUE TITLE
Accessories not shown

### ISSUE THREAD

**Issue by yokouchi86** [bwp91/homebridge-deebot#49]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?

V4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?

The issue started after I changed my account. 

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.

Deebots X1

### Please paste any relevant logs below.

```
The issue is the deebots not showing up in hoobs which previously did. This happen after I changed my account. Before this it is working perfectly such as cleaning or docking.
```

**Comment by mrbungle64** [comment]
@yokouchi86 

I need the "class" for the Deebot X1 to make it available in the underlying library.

Please check "Plugins" -> "Homebridge Deebot" -> "Settings" -> "My devices" -> "Class (Resource)"

**Comment by mrbungle64** [comment]
@yokouchi86 

I also need the **full official model name** (e.g. "Deebot X1 Omni", "Deebot X1 Turbo")

**Comment by bwp91** [comment]
Unfortunately HOOBS doesn’t offer this “my devices” option, this is only available in the Homebridge UI.

@yokouchi86 you can get the same information by using the plugin settings to turn on “Debug Logging”, then save and the bridge will restart, can you copy and paste here all the logs from the deebot plugin that appear?

**Comment by yokouchi86** [comment]
@mrbungle64 I cannot see the my devices option under hoobs as @bwp91 mentioned.

@bwp91 not sure if I am doing the right thing.
''
11/14/2021, 6:48:08 PMDeebot Bridge starting
11/14/2021, 6:48:11 PMDeebot BridgeLoaded plugin 'homebridge-deebot'
11/14/2021, 6:48:11 PMDeebot BridgeLoading 1 platforms...
11/14/2021, 6:48:11 PMDeebot BridgeDeebotInitialising plugin v4.2.7 | Node v14.18.1 | HB v1.3.4 | HOOBS v4...
11/14/2021, 6:48:11 PMDeebot BridgeDeebotPlugin initialised. Setting up accessories....
11/14/2021, 6:48:11 PMDeebot BridgeDeebotUsing ecovacs-deebot library v0.6.8.
11/14/2021, 6:48:11 PMDeebot BridgeBridge is running on port 51866.
11/14/2021, 6:48:13 PMDeebot BridgeDeebot✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91
''

**Comment by bwp91** [comment]
> The issue started after I changed my account.

Have you updated the config with your new account details? It doesn't look like the plugin is registering any devices... is your deebot device definitely linked to the account you have configured in the plugin?

**Comment by yokouchi86** [comment]
@bwp91 I am positive that I linked to the account, as I had done this yesterday and Deebot shows up in accessories. However, after I changed to my new account (old account is gone), re-setup the Deebot on the new account and reinstall the plugin, nothing appear.

**Comment by yokouchi86** [comment]
@bwp91 
![CCD13302-6263-4CF4-A43B-6F1296EC549B](https://user-images.githubusercontent.com/94289132/141678096-e73c7d4d-e7a7-4f41-b4ed-490a16c1b93e.jpeg)
![71001B84-8EC4-4EC0-B071-A44CBFE112F9](https://user-images.githubusercontent.com/94289132/141678104-9ccb8ab3-b698-423a-9aad-a7566ae610a7.jpeg)

**Comment by bwp91** [comment]
Can you go to the plugin section in the hoobs ui, do the deebot plugin and click this icon to update to the beta version:

<img width="643" alt="Screenshot 2021-11-14 at 11 01 54" src="https://user-images.githubusercontent.com/43026681/141678246-5ffd7475-8e5b-4d52-a24e-6d8c000aa44f.png">

Then select the existing deebot bridge and it will install the beta version. The bridge will then restart and can you copy and paste the logs that appear again?

**Comment by yokouchi86** [comment]
@bwp91 

1/14/2021, 7:16:32 PMDeebot BridgeLoaded plugin 'homebridge-deebot'
11/14/2021, 7:16:32 PMDeebot BridgeLoading 1 platforms...
11/14/2021, 7:16:32 PMDeebot BridgeDeebotInitialising plugin v4.2.8-beta.3 | Node v14.18.1 | HB v1.3.4 | HOOBS v4...
11/14/2021, 7:16:32 PMDeebot BridgeDeebotPlugin initialised. Setting up accessories....
11/14/2021, 7:16:32 PMDeebot BridgeDeebotUsing ecovacs-deebot library v0.7.0-alpha.1.
11/14/2021, 7:16:32 PMDeebot BridgeBridge is running on port 51866.
11/14/2021, 7:16:34 PMDeebot BridgeDeebot[0] device(s) found in your ECOVACS account.
11/14/2021, 7:16:34 PMDeebot BridgeDeebot✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
```
11/14/2021, 7:16:34 PMDeebot BridgeDeebot[0] device(s) found in your ECOVACS account.
```

The plugin isn't discovering any devices in your account 🤔

**Comment by yokouchi86** [comment]
@bwp91 yup thats where I am lost. It didnt happen previously. Let me try create another account and see how it is.

**Comment by yokouchi86** [comment]
@bwp91 not sure what happen, I restore my robot again and this time it works. Suddenly it is detected. Thanks for your prompt response, really appreciate it.

**Comment by mrbungle64** [comment]
@yokouchi86 

Please still post the "class" and full official model name 😉 
Thank you in advance

**Comment by yokouchi86** [comment]
@mrbungle64 is it this? I not sure how to find the official model name but in the add robot list is named "Deebot X1 Omni"

"class":"8bja83"

**Comment by bwp91** [comment]
Hi @yokouchi86 yes I think this is what mrbungle64 needs, and I am glad that everything seems to be working again :)

**Comment by mrbungle64** [comment]
> @mrbungle64 is it this? I not sure how to find the official model name but in the add robot list is named "Deebot X1 Omni"
> 
> "class":"8bja83"

Thanks 👍🏻
