### ISSUE TITLE
DEEBOT node issue

### ISSUE THREAD

**Issue by saiajin** [bwp91/homebridge-deebot#5]
**What issue do you have? Please be as thorough and explicit as possible.**
Deebot plugin used to work in previous version then when updated it worked for a bit then stopped working and started giving me Errors.....Updated to  node 12.19.0 and NOT compatible with Hoobs... Issue started with them.
...

**Details of your setup.**
Do you use Homebridge or HOOBS?

HOOBS
...

Which version of Homebridge/HOOBS do you have?
3.2.9

...

Which version of this plugin (homebridge-deebot) do you have?
2.1.3 
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.
10/28/2020, 12:40:40 PM [10/28/2020, 1:40:40 PM] The plugin "homebridge-deebot" requires Node version of >=12.19.0 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.
10/28/2020, 12:40:41 PM Loaded plugin 'homebridge-deebot'
10/28/2020, 12:40:41 PM [10/28/2020, 1:40:41 PM] Registering platform 'homebridge-deebot.Deebot'
...

**Comment by bwp91** [comment]
This line

> The plugin "homebridge-deebot" requires Node version of >=12.19.0 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.

is just a warning not an error. It shouldn't affect the usage of the plugin at all.

Is the plugin working for you?

**Comment by saiajin** [comment]
No not all currently...

**Comment by bwp91** [comment]
In the plugin settings if you turn on the debug setting, then restart HOOBS, and look in the logs, are there any errors that appear?

**Comment by saiajin** [comment]
Debug logging is off I believe checking again

**Comment by bwp91** [comment]
Yes, please use the plugin settings to turn it ON

**Comment by saiajin** [comment]
ran it again 
10/28/2020, 1:29:14 PM [Deebot] Plugin has finished initialising. Starting synchronisation with ECOVACS account.
10/28/2020, 1:29:14 PM [Deebot] Could not connect to ECOVACS as Cannot read property 'continent' of undefined

**Comment by saiajin** [comment]
ok turning on debug now

**Comment by saiajin** [comment]
10/28/2020, 1:32:41 PM [Deebot] Plugin has finished initialising. Starting synchronisation with ECOVACS account.
10/28/2020, 1:32:41 PM [Deebot] Could not connect to ECOVACS as TypeError: Cannot read property 'continent' of undefined
    at deebotPlatform.deebotSetup (/home/hoobs/.hoobs/node_modules/homebridge-deebot/lib/deebot-platform.js:60:51)
    at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-deebot/lib/deebot-platform.js:44:44)
    at HomebridgeAPI.emit (events.js:322:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by bwp91** [comment]
Please could you post the deebot plugin config section from the hoobs config file?
Remove your username and password, it should look something like this:

```
        {
            "countryCode": "###",
            "username": "###",
            "password": "###",
            "debug": true,
            "refreshTime": 60,
            "hideBattHumidity": true,
            "platform": "Deebot"
        },
```

**Comment by saiajin** [comment]
{
            "platform": "Deebot",
            "plugin_map": {
                "plugin_name": "homebridge-deebot"
            },
            "name": "Deebot",
            "debug": true,
            "refreshTime": 120,
            "lowBattThreshold": 20,
            "motionDuration": 30,
            "hideBattHumidity": false,
            "countryCode": "1",
            "username": "XXX",
            "password": "XXX",
            "disablePlugin": false
        }

**Comment by bwp91** [comment]
Please change this line `"countryCode": "1",` to:

`"countryCode": "US",`

assuming from the country code 1 you are indeed based in the USA?

**Comment by saiajin** [comment]
Correct! Thats working checking now...

**Comment by saiajin** [comment]
All is well!

**Comment by bwp91** [comment]
I'm glad! I'll close this now!

**Comment by saiajin** [comment]
Thank you so much!!
