### ISSUE TITLE
Device ID and Custom Areas Wiki Page Update

### ISSUE THREAD

**Issue by michaelbrawn** [bwp91/homebridge-deebot#51]
**Please explain your feature request in a one or two sentences.**
- Updated custom areas wiki page to include a prerequisite section for setting up Custom Areas. 
- Updated Configuration.md and Custom-Areas.md with information on how to find the Device ID. 
- Applied markdown rules while I was editing (https://github.com/DavidAnson/markdownlint)

Wiki's aren't PR-able so, I've pushed the changes here
- https://github.com/michaelbrawn/homebridge-deebot-wiki 
- Diff: https://github.com/michaelbrawn/homebridge-deebot-wiki/commit/6ff5f1f5080a1df39763695021f762fa25958069

**Is your feature request related to a problem? Please describe.**
- I just was confused on how to set custom areas, and where to find the device ID. So I updated the docs. 

**Any particular ECOVACS devices that this relates to?**
All

* **Anything else?**
* Hope this is helpful ✌️

**Comment by bwp91** [comment]
Hi @michaelbrawn 

Thanks for doing this, will be helpful to people in the future.

Can you check if you are able to directly edit the wiki yourself? You should be able to. Please feel free to make the changes!

**Comment by michaelbrawn** [comment]
Thanks. I do see edit access.
