### ISSUE TITLE
HB restart required to clear “offline” cloud status state

### ISSUE THREAD

**Issue by benbrookshire** [bwp91/homebridge-deebot#59]
### What issue do you have? Please be as thorough and explicit as possible.

Deebot N8+
No 100% sure, but behavior seems consistent:
If Deebot does not finish a cleaning cycle and return to charge automatically (ie gets stuck or lost), the plug-in cloud state will switch to offline and a HomeBridge restart is required to reset the state and go back online. While offline, HomeKit commands are non responsive. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HomeBridge UI/web

* Which version of Homebridge/HOOBS do you have?

1.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

OS: Debian GNU/Linux Bullseye (11)
Node v16.14.0
NPM v8.3.1
User: homebridge
/var/lib/homebridge
/var/lib/homebridge/config.json
Service mode: Yes

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?

Been using for months, not specific to this version. V4.4.1

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.

Model | DEEBOT N8 PRO+
eco-ng
85as7h (t42i)

### Please paste any relevant logs below.

![CA2BBF1C-D847-4C1C-88FA-32BF58580D8A](https://user-images.githubusercontent.com/42323694/155616847-66e2d51f-580b-4afc-87b1-87de29a68737.jpeg)

```

```

**Comment by bwp91** [comment]
Hi @benbrookshire thanks for reporting this.

@mrbungle64 any initial thoughts before I look into this properly?

**Comment by mrbungle64** [comment]
@bwp91 

> @mrbungle64 any initial thoughts before I look into this properly?

I have never heard of such behavior, nor have I ever encountered it myself.

**Comment by bwp91** [comment]
Please re-open if this still an issue :)
