### ISSUE TITLE
Issue with custom areas

### ISSUE THREAD

**Issue by aberthil** [bwp91/homebridge-deebot#65]
### What issue do you have? Please be as thorough and explicit as possible.
I can not add any custom area in the configuration despite have the map and the area in the log as explained on your wiki, for example area 9 would be living room, area 10 Dining Room, etc.
I'd like to add them into the configuration but the UI does not let me define any Custom Areas at all. Is there a way to bypass the UI and add these into the configuration using CLI, or else....

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.4.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
MacOS latest version

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
homebridge-deebot v4.4.2

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
Deebot OZMO T5

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @aberthil 

In the config-ui-x UI plugin config screen, have you entered the device ID of the deebot you are trying to add custom areas for? This is required, and the input boxes for the custom areas won't appear until the device ID has been entered.

**Comment by aberthil** [comment]
I did not indeed, where can I find it?
Thanks
Alexis

**Comment by bwp91** [comment]
Hiya did you sort this in the end?

The device id can be found in the homebridge logs when the plugin initialises

**Comment by aberthil** [comment]
Yes, sorry this is all good now
