### ISSUE TITLE
Govee H6127 [impossible]

### ISSUE THREAD

**Issue by bitfl0wer** [bwp91/homebridge-deebot#7]
* **Please explain your feature request in a one or two sentences.**

Please add Support for the Govee H6127

* **Is your feature request related to a problem? Please describe.**

* **Any particular ECOVACS devices that this relates to?**

* **Anything else?**

**Comment by bwp91** [comment]
Hi,
I assume you meant to post this on the `homebridge-govee` repo, not `homebridge-deebot` :)
Regardless of that, Govee has a concrete list of models that are supported by their API.
Unfortunately, the H6127 is not one of those, meaning support for this model is impossible at the moment (and out of my control).
I would be able to support this model **if** and when Govee update their API with an expanded supported list of models.
Thanks
