### ISSUE TITLE
Fatal error during startup

### ISSUE THREAD

**Issue by apfelnutzer** [bwp91/homebridge-deebot#73]
### What issue do you have? Please be as thorough and explicit as possible.
This plugin causes a fatal error during the startup of Homebridge:

```
# Fatal error in , line 0
# unreachable code
#FailureMessage Object: 0x75afd790
```

When I uninstall the plugin the error disappears, when I install it again it's back.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
I'm using the Homebridge UI, Homebridge is running in a docker container on a Raspberry Pi.

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.4.1 (HAP v0.10.2) 

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi, Docker image oznu/homebridge:ubuntu (latest version) - and respective Node.js/npm versions.

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
Issue occurred with version 5.0.4 and 5.0.5.

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
None. I'm waiting for/working on the support of Yeedi robots.

### Please paste any relevant logs below.
```
[6/10/2022, 10:18:32 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[6/10/2022, 10:18:33 PM] [HB Supervisor] Started Homebridge v1.4.1 with PID: 2500
[6/10/2022, 10:18:35 PM] Loaded config.json with 9 accessories and 3 platforms.
[6/10/2022, 10:18:35 PM] Loaded 0 cached accessories from cachedAccessories.
[6/10/2022, 10:18:35 PM] ---
[6/10/2022, 10:18:38 PM] Disabled plugin: homebridge-camera-ffmpeg@3.1.4
[6/10/2022, 10:18:38 PM] ---
[6/10/2022, 10:18:38 PM] The plugin "homebridge-deebot" requires Node.js version of ^14.19.3 || ^16.15.1 which does not satisfy the current Node.js version of v16.15.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x762fe790
```

... just spotted the hint in the logs re: the node.js upgrade - this is new for version 5.0.5 of the plugin - it did not occur for version 5.0.4, while the fatal error was the same. But upgrading node.js would need to be done by the container provider...

**Comment by bwp91** [comment]
Hi @apfelnutzer 

Can you have a look at this section of this wiki and potential solutions in the issue links?

https://github.com/oznu/docker-homebridge#2-container-will-not-start-on-older-versions-of-raspbian

Let me know how you get on

Thanks!

**Comment by apfelnutzer** [comment]
I had a quick lock at the issues referenced on that page and for me they look different. Anyway: As I run Homebridge in a docker container (image oznu/homebridge) I'm not able to change anything I the included OS, am I? And I don't think it would help to change the OS on the Raspberry itself (which is up to date, of course). 

Moreover as I mentioned the hint re: the outdated node.js version did not occur with 5.0.4, while the error was the same...

**Comment by bwp91** [comment]
https://github.com/oznu/docker-homebridge/issues/445#issuecomment-1150516764

This looks a very similar issue and was resolved with an OS update.

I'm not sure what changes I can make to the plugin since I don't think this is an issue with the plugin, rather an issue with the environment that the plugin is running in.

You can ignore the message about the node version. This won't have anything to do with it.

**Comment by apfelnutzer** [comment]
> [oznu/docker-homebridge#445 (comment)](https://github.com/oznu/docker-homebridge/issues/445#issuecomment-1150516764)
> 
> This looks a very similar issue and was resolved with an OS update.
> 
> I'm not sure what changes I can make to the plugin since I don't think this is an issue with the plugin, rather an issue with the environment that the plugin is running in.
> 
> You can ignore the message about the node version. This won't have anything to do with it.

You are right, that comment looks quite similar - I must have missed it earlier. I'll follow up on this later (today?)! Still the OS of my Raspberry is up to date, but we'll see...

**Comment by apfelnutzer** [comment]
@bwp91 Hm. I'm running Buster too, so maybe I should consider upgrading to Bullseye? Might have too little space left...

**Comment by apfelnutzer** [comment]
Upgrading from Buster to Bullseye solved the issue - thanks again for the hint! The log show still 

```
[6/12/2022, 2:15:21 PM] The plugin "homebridge-deebot" requires Node.js version of ^14.19.3 || ^16.15.1 which does not satisfy the current Node.js version of v16.15.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
```

though, but everything seems to work. Will now try out the new beta with my Mob Station!
