### ISSUE TITLE
Deebot, but what about Yeedi ?

### ISSUE THREAD

**Issue by Suvero** [bwp91/homebridge-deebot#74]
Hello dear dev ! You think that this plugin can work well with Yeedi robots ? As I read, yeedi and ecovacs has same hardware and these projects are the "same", regarding to some reddit's users posts.

I have one, Yeedi 2 hybrid and I wanna to add this vac to my homekit. I hope that it will be possible.

**Comment by bwp91** [comment]
You can update to the beta version of the plugin and then on the config screen select the “Use Yeedi” option and enter your username and password. Then restart.

Let us know how you get on!

**Comment by Suvero** [comment]
Can You share with me tutorial, how update it to beta release ?

**Comment by Suvero** [comment]
Btw, great job ! Good luck in future :)

**Comment by mrbungle64** [comment]
@Suvero

> Can You share with me tutorial, how update it to beta release ?

I already posted that link in the other issue 😉 
https://github.com/bwp91/homebridge-deebot/wiki/Beta-Version

**Comment by Suvero** [comment]
Great, again. Thank You so much !

**Comment by mrbungle64** [comment]
@Suvero 

Why you already closed this issue? Have you already tried if it's working?
Please give us some feedback before you close the issue 😉

**Comment by Suvero** [comment]
One more thing.. Yeedi was added and there is problem - [12/06/2022, 17:45:13] [Deebot] [0def8f50-6d72-4626-b01d-c25c78eb0884] has been reported [offline].

He is online, I can turn on via Yeedi's app.

**Comment by Suvero** [comment]
![image](https://user-images.githubusercontent.com/44507538/173241569-197024fb-be3b-4302-80c3-d3b7afb0a7f4.png)

**Comment by mrbungle64** [comment]
@Suvero

I'm currently out for jogging, but I think I already know how to fix it.
We'll let you know when a new version is available

**Comment by Suvero** [comment]
I'm excited, thanks one more time !

Maybe You had any experience with EZVIZ cameras ?

**Comment by mrbungle64** [comment]
@Suvero 

I have some questions before publishing a new version of the library:
- Has the Yeedi 2 hybrid a main brush?
- Is it possible to manually adjust the suction power?
- Has it voice reports?
- Has it mapping capabilities?

**Comment by Suvero** [comment]
My Yeedi has:
- 1x main brush
- Standard, Max and Max+
- Yes but I muted that
- Yes, my house was mapped some months ago.

**Comment by bwp91** [comment]
@Suvero 

can you reinstall the beta version of the plugin by following the same instructions as before?

The plugin version will be the same but it will reinstall updated versions of packages that it uses

**Comment by Suvero** [comment]
I do it now. One moment.

**Comment by Suvero** [comment]
![image](https://user-images.githubusercontent.com/44507538/173244904-8e5cb788-39f6-432d-84b3-41cee413f438.png)
Same.

**Comment by bwp91** [comment]
Can you show logs before this? To see all the logs since restarting?

**Comment by Suvero** [comment]
![image](https://user-images.githubusercontent.com/44507538/173245082-dff95519-7173-4429-bf46-179a420c5133.png)

**Comment by Suvero** [comment]
![image](https://user-images.githubusercontent.com/44507538/173245132-80d41141-62a7-4efb-8aec-fa3a535f8100.png)
yes, it's hybrid 2

**Comment by bwp91** [comment]
and one picture of the logs before this too please!

**Comment by Suvero** [comment]
![image](https://user-images.githubusercontent.com/44507538/173245272-1161af4e-8180-41b6-9d0d-87703fe279bc.png)
![image](https://user-images.githubusercontent.com/44507538/173245278-05cb2713-97a5-426d-9f67-eaa295da43bc.png)

**Comment by Suvero** [comment]
![image](https://user-images.githubusercontent.com/44507538/173245360-adf0fb9e-8d0f-43f6-975c-5d2877117924.png)

**Comment by mrbungle64** [comment]
@Suvero 

It's still version 0.8.3-alpha.2 of the library
Please wait until @bwp91 has published a new beta version of the plugin.

**Comment by bwp91** [comment]
@mrbungle64 @Suvero 

New beta for this plugin has been published - 5.0.6-beta.4

Suvero please update to this using the steps as before!

**Comment by Suvero** [comment]
Done. Robot starts and stops - right button in homekit working as Charging, so working well. Fix only icon of Vac in homekit UI and would be cool :)

**Comment by mrbungle64** [comment]
> Done. Robot starts and stops - right button in homekit working as Charging, so working well.

Great 👍🏻 

>  Fix only icon of Vac in homekit UI and would be cool :)

What icon do you mean?

**Comment by bwp91** [comment]
There is no vacuum icon in homekit there is not even such an accessory type. this is why it is displayed as switches

**Comment by Suvero** [comment]
You can use best-choosen fan icon, it's better I think than button :D
