### ISSUE TITLE
Configure Spot Areas

### ISSUE THREAD

**Issue by ndhome** [bwp91/homebridge-deebot#95]
Hey there
Thank you for this great plugin, really easy to follow, also for someone like me, that is very new to coding.
I got problems, setting up the Spot areas.
I put all the information in homebridge (mapSpotAreaID's, and Description), restarted the bridge, but in the Eve App, the numbers are not showing, as mentioned in your guide.
What am I doing wrong? Could you help me with that?
Best regards Andy

**Comment by bwp91** [comment]
Hi @ndhome apologies that you never got a reply on here.
Is there anything I can still help you with?
