### ISSUE TITLE
Expose button instead using Eve app

### ISSUE THREAD

**Issue by jp-lno** [bwp91/homebridge-deebot#99]
* **Please explain your feature request in a one or two sentences.**

Instead of being dependent on Eve app you could expose button for each zone.  

* **Is your feature request related to a problem? Please describe.**

Actually Eve app crash on my iPhone (all is up to date). All my automations actions stopped working. 
This issue is not related to this plugin. But I’ve tried to find a workaround to stop using Eve app and have a fully embedded solution. 

* **Any particular ECOVACS devices that this relates to?**

Nope

* **Anything else?**

This feature has been implemented in another homebridge plugin. But I prefer this one and I trust and support more this developer

Related project using the required feature : 
 https://github.com/nicoduj/homebridge-deebotecovacs#readme

**Comment by bwp91** [comment]
is Eve app still crashing for you?

**Comment by jp-lno** [comment]
Yes. So I’ve deleted the app And I’ve switched to [Deebotecovacs](https://github.com/nicoduj/homebridge-deebotecovacs#readme) plugin. That allow me to setup my Deebot directly in home app and without needs of external app 🙂
